export const Projects = {

  gameTime: {
    imgURL: '/lib/imgs/phlyingphish.png',
    gifURL: '/lib/imgs/phlyingphish.gif',
    hostURL: 'https://milkman90.github.io/game-time/',
    title: 'Phlying Phish',
    description: 'A side scrolling helicopters clone with the goal of eating mushroom powerups and getting the high score. Try to keep the jams going! Trey does not like to be interrupted.',
    tech: ['JavaScript', 'HTML5 Canvas'],
    githubURL: 'https://github.com/MilkMan90/game-time',
  },
  netwerker: {
    imgURL: '/lib/imgs/netwerker.png',
    gifURL: '/lib/imgs/netwerker.gif',
    hostURL: 'https://netwerker-3d622.firebaseapp.com/',
    title: 'Netwerker',
    description: 'Save all the new people you meet into this networking app with a firebase backend. Each user logs in with their Google account and can save contacts to their own database which is automatically retrieved upon login',
    tech: ['JavaScript', 'React', 'Firebase'],
    githubURL: 'https://github.com/MilkMan90/netwerker',
  },
  weatherMe: {
    imgURL: '/lib/imgs/weatherme.png',
    gifURL: '/lib/imgs/weatherme.gif',
    hostURL: 'https://milkman90.github.io/weathrly/',
    title: 'WeatherMe',
    description: 'Built with react, WeatherMe is a sleek, responsive weather app utilizing the WundergroundAPI - view alerts and 24 hour weather in any area supported by the API.',
    tech: ['JavaScript', 'React', 'Firebase'],
    githubURL: 'https://github.com/MilkMan90/weathrly',
  },
  shootTheBreeze: {
    imgURL: '/lib/imgs/shootthebreeze.png',
    gifURL: '/lib/imgs/shootthebreeze.gif',
    hostURL: 'https://shootthebreeze-8ee5f.firebaseapp.com',
    title: 'ShootTheBreeze',
    description: 'A real-time messaging app utilizing firebase storage and retrieval - a history of all messages/contributing users is kept in the database.',
    tech: ['JavaScript', 'React', 'Firebase'],
    githubURL: 'https://github.com/MilkMan90/shoot-the-breeze',
  },
  toDoBox: {
    imgURL: '/lib/imgs/2dolist.png',
    gifURL: '/lib/imgs/2dolist.gif',
    hostURL: 'https://milkman90.github.io/2DoBox/',
    title: '2DoList',
    description: 'A single page React app which stores To-Dos, allows for checking-off completion, sorting by importance, and limiting the number of tasks visible',
    tech: ['JavaScript', 'React'],
    githubURL: 'https://github.com/MilkMan90/2DoBox',
  },
  weatherDux: {
    gifURL: '/lib/imgs/weatherDux.gif',
    imgURL: '/lib/imgs/weatherDuxIcon.png',
    hostURL: 'https://hilarylewis92.github.io/weather-forecast/#/?_k=myzv4x',
    title: 'weatherDux',
    description: 'A single page React/Redux app that utilizes the WeatherUnderground API to retrive weather and pin it to the page to save for later',
    tech: ['JavaScript', 'React', 'Redux'],
    githubURL: 'https://github.com/MilkMan90/weather-forecast',
  },
  dashboard: {
    imgURL: '/lib/imgs/dashboard.png',
    gifURL: '/lib/imgs/dashboard.gif',
    hostURL: 'http://turingdashboard.herokuapp.com/',
    title: 'Turing Dashboard',
    description: 'A Dashboard powered by a Rails server for all things Turing operations',
    tech: ['JavaScript', 'React', 'Victory-D3'],
    githubURL: 'https://github.com/MilkMan90/turing_dashboard',
  },
};
